/// A Solidity function's state mutability.
///
/// Mirrors [`alloy_sol_type_parser::StateMutability`] but is defined here to avoid adding a
/// dependency on the parser crate at runtime.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum StateMutability {
    /// Pure functions promise not to read from or modify the state.
    Pure,
    /// View functions promise not to modify the state.
    View,
    /// Nonpayable functions promise not to receive Ether.
    ///
    /// This is the solidity default.
    NonPayable,
    /// Payable functions make no promises.
    Payable,
}

impl StateMutability {
    /// Returns the string representation of the state mutability.
    #[inline]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Pure => "pure",
            Self::View => "view",
            Self::NonPayable => "nonpayable",
            Self::Payable => "payable",
        }
    }
}

impl core::fmt::Display for StateMutability {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Descriptor for a single function in an ABI manifest.
///
/// Generated by the `sol!` macro when `#[sol(abi)]` is enabled.
/// Provides compile-time metadata about each function for introspection,
/// dispatch, and tooling.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct MethodSpec {
    /// 4-byte function selector.
    pub selector: [u8; 4],
    /// Solidity function name (camelCase).
    pub name: &'static str,
    /// Rust method name (snake_case).
    pub rust_name: &'static str,
    /// Function state mutability.
    pub state_mutability: StateMutability,
    /// Number of input parameters.
    pub param_count: usize,
    /// Whether the function has a return value.
    pub has_return: bool,
}
